version: "3.9"
services:
  postgres_db:
    container_name: db_container
    image: postgres:latest
    restart: always
    ports: 
      - 5432:5432
    env_file:
      - .env
    volumes: 
      - mongo_db:/var/lib/postgresql/data

  node_api:
    container_name: api_container
    build: .
    ports: 
      - 8000:8000
    volumes: 
      - .:/user/src/app
    env_file:
      - .env
    depends_on:
      - postgres_db

volumes: 
  mongo_db: 